# -*- coding: utf-8 -*-
"""Lista (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Su179you30tBDfIQfRUQp3-I-ykWs_ke
"""

import enum
class ListaVehiculo (enum.Enum):
  campero = 1
  moto = 2
  camioneta = 3
  busetas = 4
  carro = 5



