# -*- coding: utf-8 -*-
"""LugarParqueadero (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FSoO2sZAurD-bPvdd4ORapcaa4_35Drb
"""

class LugarParqueo:
  def DefinirLugarVehiculo(int,self):
    "definir el lugar donde se va a alojar el vehiculo"
  def Vehiculo(vehiculo):
    "definir el tipo de vehiculo"



