# -*- coding: utf-8 -*-
"""LugarParqueadero (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FSoO2sZAurD-bPvdd4ORapcaa4_35Drb
"""
import Vehiculo

class LugarParqueo:
    "atributos"
    def DefinirLugarVehiculo(self):
        input("definir el lugar donde se va a alojar el vehiculo")
        
    "medotos"
    
    def DestinarUnSitioDeParqueo(self):
        print("destinar el lugar de parqueo")
 


