# -*- coding: utf-8 -*-
"""LugarParqueadero (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FSoO2sZAurD-bPvdd4ORapcaa4_35Drb
"""
import Vehiculo

class LugarParqueadero:
    "atributos"
    def __init__(self, LugarParqueadero:int, Vehiculo : Vehiculo):
        self.LugarParqueadero : LugarParqueadero
        self.Vehiculo = Vehiculo

        
    "medotos"
    
    def DestinarUnSitioDeParqueo(self):
        print("destinar el lugar de parqueo")
 


