# -*- coding: utf-8 -*-
"""Parqueadero (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O75nHSqZC3quY70YX_rCKvO1UGP3bLcM
"""
import LugarParqueadero
import Alerta

class Parqueadero:
    "atributos"
    def NumeroDeParqueaderos(int):
        input("Ingresar el numero de parqueaderos")
    def NumeroPisosDeParqueadero(int):
        input("ingresar el numero de pisos que posee el parqueadero ")
    def Alerta(alerta):
        input("ingresar alerta que posea")
    def NumeroDeEspaciosDeElementos(int):
        input( "ingresar el numero de lugares disponibles en los cuales posea espacio para guardar elementos secundarios del vehiculo ")
    def LugarParqueadero(LugarParqueadero):
        input("ingresar lugar parqueadero ")

    def __init__(self):
      self.Alerta = Alerta

    def _init_(self):
      self.LugarParqueadero = LugarParqueadero()

    "metodos"
    def RegistrarElTotalDeEspaciosDelParqueadero(self, numeroDeParqueaderos):
        print("numero de parqueaderos que hay en el parqueadero")
    
    def RegistrarNumeroDePisosDeParqueaderos(self, numeroDePisosDeParqueadero):
        print("el numero de pisos de parqueos")