# -*- coding: utf-8 -*-
"""Parqueadero (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O75nHSqZC3quY70YX_rCKvO1UGP3bLcM
"""



class Parqueadero:
  def NumeroDeParqueaderos(int):
    "Ingresar el numero de parqueaderos"
  def NumeroPisosDeParqueadero(int):
    "ingresar el numero de pisos que posee el parqueadero "
  def Alerta(alerta):
    "ingresar alerta que posea"
  def NumeroDeEspaciosDeElementos(int):
    "ingresar el numero de lugares disponibles en los cuales posea espacio para guardar elementos secundarios del vehiculo "
  def LugarParqueadero(LugarParqueadero):
    "ingresar lugar parqueadero "

    def _init_(delf):
      self.Alerta = Alerta()

    def _init_(delf):
      self.LugarParqueadero = LugarParqueadero()



