# -*- coding: utf-8 -*-
"""Tarifa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZEKA3VJdNVcGTiaJKDta9PQBXH82nGg
"""

class Tarifa:
  def ValorTarifaPorHora(int):
    "ingresar el valor de hora"
  def Vehiculo(Vehiculo):
    "clase Vehiculo"
  def Tiempo(Tiempo):
    "Tiempo"

