# -*- coding: utf-8 -*-
"""Tarifa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZEKA3VJdNVcGTiaJKDta9PQBXH82nGg
"""
import Vehiculo
import Tiempo


class Tarifa:
    "atributos"
    def ValorTarifaPorHora(int):
        input("ingresar el valor de hora")
    
    "metotos"
    
    def __init__(self):
        self.Vehiculo = Vehiculo()
        self.Tiempo = Tiempo
      

