# -*- coding: utf-8 -*-
"""Tarifa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZEKA3VJdNVcGTiaJKDta9PQBXH82nGg
"""
import Vehiculo
import Tiempo


class Tarifa:
    
    Vehiculo : Vehiculo

    def __init__(self,ValorTarifaPorHora : int, Tiempo:Tiempo):
        self.ValorTarifaPorHora : ValorTarifaPorHora
        self.Tiempo : Tiempo 
    
    
    "metotos"
    
    def RegistrarTarifa(ValorTarifaPorHora):
        print("valor de la tarifa")
        
    def DevolverElValorAPagar(Tiempo):
        print("devuelta")
