# -*- coding: utf-8 -*-
"""ticket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSkb0eH4yaSN-2_teaMjbaDY_kdo33Sd
"""

class TicketIngreso:
  def HoraDeEntrada(string):
    "dijitar la hora de ingreso del vehiculo"
  def _init_(delf):
    delf.Vehiculo = Vehiculo()

