# -*- coding: utf-8 -*-
"""ticket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jSkb0eH4yaSN-2_teaMjbaDY_kdo33Sd
"""
import Vehiculo

class TicketIngreso:
    "atributos"
    def HoraDeEntrada(string):
        int("dijitar la hora de ingreso del vehiculo")
    def _init_(self):
        self.Vehiculo = Vehiculo

    "metodos"
    def ImprimirTicketIngreso(self):
        print("informacion de ticket")
        
        