# -*- coding: utf-8 -*-
"""Tiempo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYJPyFJNM90tfv3csNEqA1_gcfnlpfQf
"""

class Tiempo:
   def TiempoDeEntrada(string):
       input("insertar el tiempo de entrada del vehiculo")
   def TiempoDeSalida(string):
       input("insetar el tiempo de salida")
   
   "metodos"
   
   def RegistrarTiempoDeEstadia(self,TiempoDeEntrada):
       print("tiempo de entrada")
    
   def RegistrarTiempoDeSalida(self,TiempoDeSalida):
       print("tiempo de salida")
