# -*- coding: utf-8 -*-
"""Tiempo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYJPyFJNM90tfv3csNEqA1_gcfnlpfQf
"""

class Tiempo:
  def TiempoDeEntrada(string):
    "insertar el tiempo de entrada del vehiculo"
  def TiempoDeSalida(string):
    "insetar el tiempo de salida"

