# -*- coding: utf-8 -*-
"""Tiempo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYJPyFJNM90tfv3csNEqA1_gcfnlpfQf
"""

class Tiempo:
   
   def __init__(self, TiempoDeEntrada: str, TiempoDeSalida: str):
       self.TiempoDeEntrada : TiempoDeEntrada 
       self.TiempoDeSalida : TiempoDeSalida 
       
  
   #"metodos"
   
   def RegistrarTiempoDeEstadia(self,TiempoDeEntrada):
       print("Tiempo de entrada",TiempoDeEntrada)
    
   def RegistrarTiempoDeSalida(self,TiempoDeSalida):
       print("Tiempo de salida",TiempoDeSalida)
