# -*- coding: utf-8 -*-
"""Vehiculo (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msoLbHQF6aCv_0rRZuovTm_s0FqEXMsD
"""
import ListaTipoVehiculo
class Vehiculo:
    
    def __init__(self, Placa: str, TipoVehiculo : int(ListaTipoVehiculo)):
        self.Placa : Placa
        self.TipoVehiculo : ListaTipoVehiculo
        
    "metodos"
    
    def RegistrarVehiculo(self):
        print("Vehiculo regitrado en el parqueadero")
    
    
    
    
        
      
      

  

