# -*- coding: utf-8 -*-
"""Vehiculo (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msoLbHQF6aCv_0rRZuovTm_s0FqEXMsD
"""
import ListaTipoVehiculo
class Vehiculo:
    "atributos"
    def Placa(string):
        input("Digite la placa del vehiculo")
        
    def __init__(self):
        self.ListaTipoVehiculo = ListaTipoVehiculo
        
    "metodos"
    
    def RegistrarVehiculo(self):
        print("vehiculo regitrado")
    
    
    
    
        
      
      

  

