# -*- coding: utf-8 -*-
"""Vehiculo (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1msoLbHQF6aCv_0rRZuovTm_s0FqEXMsD
"""

class Vehiculo:
  def TipoVehiculo(num,ListaVehiculo):
    "tipo vehiculo"

